# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camara.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_camara(object):
    def setupUi(self, camara):
        camara.setObjectName("camara")
        camara.resize(358, 350)
        camara.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.title = QtWidgets.QLabel(camara)
        self.title.setGeometry(QtCore.QRect(50, 40, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(118, 209, 98);\n"
"color: rgb(0, 0, 0);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.sqr = QtWidgets.QLabel(camara)
        self.sqr.setGeometry(QtCore.QRect(30, 20, 301, 301))
        self.sqr.setStyleSheet("background-color: rgb(143, 143, 143);")
        self.sqr.setFrameShape(QtWidgets.QFrame.Box)
        self.sqr.setText("")
        self.sqr.setScaledContents(True)
        self.sqr.setObjectName("sqr")
        self.flash = QtWidgets.QPushButton(camara)
        self.flash.setGeometry(QtCore.QRect(140, 280, 81, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.flash.setFont(font)
        self.flash.setStyleSheet("background-color: rgb(118, 208, 98);\n"
"color: rgb(0, 0, 0);")
        self.flash.setObjectName("flash")
        self.photo = QtWidgets.QLabel(camara)
        self.photo.setGeometry(QtCore.QRect(110, 120, 141, 151))
        self.photo.setStyleSheet("background-color: rgb(143, 143, 143);")
        self.sqr.setFrameShape(QtWidgets.QFrame.Box)
        self.photo.setText("")
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.sqr.raise_()
        self.title.raise_()
        self.flash.raise_()
        self.photo.raise_()

        self.retranslateUi(camara)
        QtCore.QMetaObject.connectSlotsByName(camara)

    def retranslateUi(self, camara):
        _translate = QtCore.QCoreApplication.translate
        camara.setWindowTitle(_translate("camara", "Form"))
        self.title.setText(_translate("camara", "BIOMETRÍA"))
        self.flash.setText(_translate("camara", "Tomar foto"))
